[package]
name = "trixter-osec-puppet-master"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "trixter-osec-puppet_master"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
idl-build = ["trixter-osec-anchor-lang/idl-build"]

[dependencies]
trixter-osec-anchor-lang = { path = "../../../../../lang" }
trixter-osec-puppet = { path = "../puppet", features = ["cpi"] }
